name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/whisper_live_test.yml'
      - '.github/workflows/cuda_test.yml'
      - '.github/workflows/tests/**'

permissions:
  contents: read

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  whisper_live_test:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/whisper_live_test.yml

  cuda_test:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/cuda_test.yml
